### ISSUE TITLE
imp : Heroku up

### ISSUE THREAD

**Issue by RieMatsui** [RieMatsui/instagramApp#38]
Herokuにデプロイする。

[9-1 Herokuを使ってサービスを世の中に公開しよう（Mac）](https://www.techpit.jp/courses/378648/lectures/9970921)
SQLite3がHeroku に対応してないので、PostgreSQLをインストールする。

[SQLite on Heroku](https://devcenter.heroku.com/articles/sqlite3)
config/database.ymlを編集します。

```
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
```
